#!/usr/bin/env python

import csv
import sys
import gzip
import pprint

entry_blocks = []
current_block = []

filename = sys.argv[1]

if filename.endswith('.gz'):
    f = gzip.open(filename)
else:
    f = open(filename )

csv_reader = csv.reader(f, delimiter=',', quotechar='"')
csv_writer = csv.writer(sys.stdout, delimiter=',', quotechar='"', lineterminator='\n')

for row in csv_reader:
    row = [field.strip() for field in row] # Strip left and right whitespace per field
    current_block.append(row)

    for field in row:
        if 'SOID:' in field:
            entry_blocks.append(current_block)
            current_block = []

for block in entry_blocks:
    first, last, second_last  = block[0], block[-1], block[-2]

    name, booking_no, agency, abn = first[0], first[1], first[4], first[5]
    address, city, pob = second_last[:3]
    release_date, release_code, soid = last[:3]

    head = [soid, booking_no, name, agency, abn, address, city, pob, release_date, release_code]

    first_charge = block[1][1:4]

    csv_writer.writerow(head + first_charge)

    # If more than one charge
    #
    if len(block) > 3:
        for l in block[2:-3]:
            charge = l[1:4]
            csv_writer.writerow(head + charge)

f.close()


# Example block:
#
# ['ARRINGTON,JESSE', '99068448', '', '', 'HCSO', '2650', '']
# ['B / M / N / 01/15/1946', 'CAPIAS', 'CONSUMING ON STREETS', '41C', '9933579MO', '', ''],
# ['', 'CAPIAS', 'POSSESSION OF OPEN CONTAINER', '41C', '9922942MO', '', ''],
# ['', '', '', '', '', '', ''],
# ['ADDRESS: 7800 NEBRASKA AV N', 'TAMPA', 'POB: FL', '', '', '', '']
# ['RELEASE DATE: 01/19/2000', 'RELEASE CODE: TIME SERVED', 'SOID: 308163', '', '', '', '']
